version: '2'

services:
  limesurvey:
    image: docker.dru-id.com:5000/druid/limesurvey:2.62
    ports:
      - 8082:80
    env_file: limesurvey.env
    links:
      - db:limesurvey.db
    # command: ["/usr/local/bin/wait-for-mysql.sh"]
    volumes:
      - ./src/limesurvey:/var/www/html
  db:
    image: mysql:5.7
    env_file: limesurvey.env
      
